# Generated by Django 3.0.6 on 2020-05-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('mileage', models.IntegerField(null=True)),
                ('female', models.BooleanField(default=True, null=True)),
                ('registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
