# Generated by Django 3.0.6 on 2020-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mileage',
        ),
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
