# Generated by Django 3.0.6 on 2020-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200530_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='female',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
