# Generated by Django 3.0.6 on 2020-06-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200530_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.CharField(max_length=15, null=True)),
                ('paid', models.FloatField(null=True)),
                ('payment_date', models.DateField(blank=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, max_length=200, null=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.client')),
            ],
        ),
    ]
