# Generated by Django 3.0.6 on 2020-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='paid',
            new_name='payment_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash')], max_length=100, null=True),
        ),
    ]
