# Generated by Django 3.0.6 on 2020-06-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200601_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payment_amount',
            new_name='paid',
        ),
    ]
