# Generated by Django 3.0.6 on 2020-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200601_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=100, null=True),
        ),
    ]
