# Generated by Django 3.0.6 on 2020-06-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200601_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'Card'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='Card', max_length=100, null=True),
        ),
    ]
