# Generated by Django 3.0.6 on 2020-06-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
