# Generated by Django 3.0.6 on 2020-06-02 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200602_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.instructor'),
        ),
    ]
