# Generated by Django 3.0.6 on 2020-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_lesson_instructedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=200, null=True)),
                ('meaning', models.CharField(max_length=200, null=True)),
                ('frequency', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='sessions',
            field=models.IntegerField(null=True),
        ),
    ]
